Linac edm2pydm
lnls-sirius/hla pull request #524
Opened 2022-03-09 17:47 UTC by RafaelLyra8

- Migration of Linac's BPM Interface from EDM to PyDM

![Selection_001](https://user-images.githubusercontent.com/63302930/157500300-a5c296cf-8075-41be-9efe-1424029c5807.png)

2022-03-22 21:49 UTC, murilobalves approved these changes

2022-03-22 21:52 UTC, xresende approved these changes

2022-03-24 13:52 UTC, fernandohds564 requested changes

2022-03-24 13:52 UTC, fernandohds564 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +        if(style == 0):
no need for the parenthesis in if statements.

2022-03-24 13:52 UTC, fernandohds564 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
>  from siriushla.as_di_bpms.base import GraphWave
leave an empty line between imports of external libraries and our own.
Also, you can import this class with relative import:
`from ..as_di_bpms.base import GraphWave`.

2022-03-24 13:52 UTC, fernandohds564 commented on pyqt-apps/scripts/sirius-hla-li-di-bpms.py
> +sys.exit(app.exec_())
need an empty new line at the end of the file.

2022-03-24 18:00 UTC, anacso17 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +        elif(style == 1 or style == 2 or style == 4):
here you can use 
`elif style in [1, 2, 4]:`

2022-03-24 18:02 UTC, anacso17 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +                  or title == "Cycle"):
equivalently:
`if title in ["Trigger Cnt", "Cycle"]:`

2022-03-24 18:04 UTC, anacso17 commented on pyqt-apps/scripts/sirius-hla-li-di-bpms.py
> +    description="Run Interface of Specified Screen.")
maybe `"Run Interface of Specified BPM."`

2022-03-24 18:05 UTC, anacso17 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +        self.prefix = prefix
I think this line is not necessary

2022-03-24 18:29 UTC, fernandohds564 requested changes
very nice @RafaelLyra8 ! Just a few more changes and we are good to merge!

2022-03-24 18:29 UTC, fernandohds564 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +
there is no empty line after the docsctring of a method

2022-03-24 18:29 UTC, fernandohds564 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +            if (title == "Trigger Cnt"
do you really need this line break here? it seems the code would fit in a single line.

2022-03-24 18:29 UTC, fernandohds564 commented on pyqt-apps/siriushla/li_di_bpms/bpm_main.py
> +        elif(style == 1 or style == 2 or style == 4):
no need for parenthesis in a if clause.

2022-03-24 18:39 UTC, fernandohds564 approved these changes
very nice PR! Congrats!

2022-03-24 18:43 UTC, merged