Improve SpectrogramView
lnls-sirius/hla pull request #549
Opened 2022-07-12 20:30 UTC by anacso17

- Use current ViewBox menu instead of creating new one
- Fix bug in mouseModeEvent when imageItem is empty
- Make it possible to change the view range to zoom 

Illustrating:
![Screenshot from 2022-07-12 17-27-39](https://user-images.githubusercontent.com/21130191/178589401-043a86e7-d05f-4967-b95b-e6420379c288.png)

![Screenshot from 2022-07-12 17-28-21](https://user-images.githubusercontent.com/21130191/178589397-8f850743-ae36-4e0a-87f3-e33e92d1ee13.png)

2022-07-13 13:47 UTC, murilobalves approved these changes

2022-07-14 11:18 UTC, fernandohds564 requested changes

2022-07-14 15:57 UTC, anacso17 commented on pyqt-apps/siriushla/widgets/spectrogram_view.py
> +        limsx = _linear_interpolation(
I used it for standardization, but I understand that maybe it is an overkill.
Done!

2022-07-14 17:46 UTC, fernandohds564 approved these changes

2022-07-14 19:39 UTC, xresende approved these changes

2022-07-14 20:08 UTC, merged