Add Parameters to the ImageView Widget
lnls-sirius/hla pull request #638
Opened 2023-07-05 12:20 UTC by RafaelLyra8

2023-07-11 11:02 UTC, murilobalves approved these changes

2023-07-13 12:24 UTC, xresende commented
@RafaelLyra8 , I tried this PR on lnls451-linux and noticed that the added graphical elements seem to be working but the original DVF image is not showing up. The idea is to have these graphical elements drawn on top of the raw beam image, an hence to be able to check through the graphical elements whether the fit parameters are good.

2023-07-13 12:27 UTC, xresende requested changes
@RafaelLyra8 , I tried this PR on lnls451-linux and noticed that the added graphical elements seem to be working but the original DVF image is not showing up. The idea is to have these graphical elements drawn on top of the raw beam image, an hence to be able to check through the graphical elements whether the fit parameters are good.

2023-07-13 13:05 UTC, anacso17 commented
@xresende @RafaelLyra8 I just pushed a possible fix to the behavior Ximenes had observed. Ximenes, could you try again?

2023-07-17 19:29 UTC, anacso17 approved these changes

2023-07-17 19:45 UTC, xresende approved these changes

2023-07-17 19:45 UTC, merged