Add FDL detail window
lnls-sirius/hla pull request #698
Opened 2024-06-13 13:32 UTC by JAFeltran

Adds the `Open FDL` button to the overview window that opens an auxiliary window with fdl information when clicked. This auxiliary window contains control information, incluind setpoints and readbacks for some PVs. For `Trigger Delay`, the setpoint spinbox only appears once a unit is chosen on the combo box. The window also displays graphs for the amplitude and phase of multiple PVs. A series of checkboxes allows the user to choose which curves will be included on the graphs.

![status_with_fdl_gui](https://github.com/lnls-sirius/hla/assets/80780363/6ec401d7-0171-4fa4-b322-b616e2b4d8d2)

![fdl_window_gui](https://github.com/lnls-sirius/hla/assets/80780363/3de64aca-6c9a-40f3-ae49-7f66e8334b8c)

2024-06-13 14:57 UTC, anacso17 commented on pyqt-apps/siriushla/as_rf_control/control.py
> +        self.pb_openfdl = SiriusPushButton(label='Open FDL', icon=qta.icon('fa5s.external-link-alt'), releaseValue=0, parent=self)
here you can use a simple QPushButton, only specifying the icon and the label

2024-06-13 14:58 UTC, anacso17 commented on pyqt-apps/siriushla/as_rf_control/control.py
> +        self._ld_fdl = QLabel('<h4>FDL</h4>', self, alignment=Qt.AlignLeft)
Maybe the group can be "Auxiliary windows", to be possible to group any other GUI in the future

2024-06-13 14:59 UTC, anacso17 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +
use 2 lines between classes

2024-06-13 15:03 UTC, anacso17 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +    def setupCurve(self, signal, time, idx):
avoid using the name "time", because of the python library that has this name
maybe rename to timebase

2024-06-13 15:05 UTC, anacso17 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +        self.lb_delay_us.setVisible(text == 'us' and text != 'Choose a unit')
it seems you can simplify:
```
self.sb_delay_sample.setVisible(text == 'Sample units')
self.lb_delay_sample.setVisible(text == 'Sample units')
self.sb_delay_us.setVisible(text == 'us')
self.lb_delay_us.setVisible(text == 'us')

2024-06-13 16:35 UTC, anacso17 approved these changes

2024-06-13 19:27 UTC, David-Daminelli approved these changes

2024-06-14 20:31 UTC, fernandohds564 requested changes
@JAFeltran, I noticed the code is not following the guidelines we generally use. Could you please check for incompatibilities? We are trying to adopt ruff or black as our default formatter. For more details, please, check this PR: lnls-sirius/dev-packages#1061

2024-06-14 20:31 UTC, fernandohds564 commented on pyqt-apps/siriushla/as_rf_control/control.py
> +        self.pb_openfdl = QPushButton(text=' FDL', icon=qta.icon('fa5s.external-link-alt'), parent=self)
this line has more than 79 characters.

2024-06-14 20:31 UTC, fernandohds564 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +            '<h4>Force FDL Trigger (SW Interlock):</h4>', self, alignment=Qt.AlignRight | Qt.AlignVCenter),
This one too.

2024-06-14 20:31 UTC, fernandohds564 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +        lay.addWidget(QLabel('<h4>FDL ADCs Raw Data:</h4>', self, alignment=Qt.AlignRight | Qt.AlignVCenter),
this one too.

2024-06-14 20:31 UTC, fernandohds564 commented on pyqt-apps/siriushla/as_rf_control/details.py
> +                           2, 2)
wrong identation.

2024-06-17 12:39 UTC, murilobalves approved these changes

2024-06-18 16:44 UTC, JAFeltran commented
> @JAFeltran, I noticed the code is not following the guidelines we generally use. Could you please check for incompatibilities? We are trying to adopt ruff or black as our default formatter. For more details, please, check this PR: [lnls-sirius/dev-packages#1061](https://github.com/lnls-sirius/dev-packages/pull/1061)

I've applied ruff to format code pertinent to this PR. The rest of the file still contains some formatting inconsistencies, which I didn't correct to avoid polluting this PR's diff.

2024-06-18 18:05 UTC, fernandohds564 approved these changes

2024-06-24 13:02 UTC, merged